name: Forum App CI/CD

on:
  push:
    branches: [ "main", "master", "develop" ] # Sesuaikan dengan nama branch Anda
  pull_request:
    branches: [ "main", "master" ]         # Sesuaikan dengan nama branch utama Anda

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Anda bisa menggunakan versi Node.js lain jika perlu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # Menggunakan npm ci untuk instalasi yang lebih cepat dan konsisten di CI

    - name: Run linters
      run: npm run lint

    - name: Run tests (Unit, Integration, E2E)
      run: npm run ci:test # Perintah ini akan menjalankan 'npm test && npm run e2e'
      env:
        # Jika tes E2E Anda memerlukan variabel lingkungan, definisikan di sini
        # atau lebih baik lagi, gunakan GitHub Secrets (lihat di bawah)
        CYPRESS_VALID_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
        CYPRESS_VALID_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
        # Pastikan baseUrl di cypress.config.js adalah http://localhost:3000
        # karena start-server-and-test akan menjalankan server di port tersebut
        # CI: true # Beberapa library mungkin berperilaku berbeda jika CI=true

    - name: Build application (opsional, untuk verifikasi build)
      run: npm run build
      env:
        CI: false # Jika build Anda gagal karena warning yang dianggap error oleh CRA