name: Forum App CI/CD

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linters
      run: npm run lint

    - name: Run tests (Unit, Integration, E2E)
      run: npm run ci:test # Ini akan menjalankan 'npm test && npm run e2e'
                          # dan 'npm run e2e' sekarang memanggil 'start:ci-e2e'
      env:
        CYPRESS_VALID_EMAIL: ${{ secrets.CYPRESS_TEST_EMAIL }}
        CYPRESS_VALID_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
        WAIT_ON_TIMEOUT: 300000 # Tetap pertahankan timeout yang panjang
        CI: true # Untuk npm test dan keseluruhan step, tapi start server akan CI=false

    - name: Build application (opsional, untuk verifikasi build)
      run: npm run build
      env:
        CI: false